In [1]:
import pandas as pd
from matplotlib import pyplot as plt
from datetime import datetime
import seaborn as sns

%matplotlib inline

In [2]:
atp20 = pd.read_csv('./data/atp_matches_2020.csv')

In [3]:
atp20.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2020-8888,Atp Cup,Hard,24,A,20200106,300,104925,NaN,NaN,...,51.0,39.0,6.0,10.0,6.0,8.0,2.0,9055.0,1.0,9985.0
1,2020-8888,Atp Cup,Hard,24,A,20200106,299,105138,NaN,NaN,...,35.0,21.0,6.0,9.0,5.0,10.0,10.0,2335.0,34.0,1251.0
2,2020-8888,Atp Cup,Hard,24,A,20200106,298,104925,NaN,NaN,...,57.0,35.0,25.0,14.0,6.0,11.0,2.0,9055.0,5.0,5705.0
3,2020-8888,Atp Cup,Hard,24,A,20200106,297,105583,NaN,NaN,...,54.0,39.0,14.0,12.0,0.0,1.0,34.0,1251.0,17.0,1840.0
4,2020-8888,Atp Cup,Hard,24,A,20200106,296,104745,NaN,NaN,...,55.0,37.0,10.0,14.0,1.0,5.0,1.0,9985.0,18.0,1775.0

In [4]:
ao20 = atp20[atp20.tourney_name == 'Australian Open']

In [5]:
ao20.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
167,2020-580,Australian Open,Hard,128,G,20200120,100,104745,1,NaN,...,64.0,32.0,8.0,11.0,10.0,18.0,1.0,10235.0,73.0,743.0
168,2020-580,Australian Open,Hard,128,G,20200120,101,105643,NaN,NaN,...,60.0,43.0,24.0,15.0,8.0,10.0,76.0,711.0,59.0,891.0
169,2020-580,Australian Open,Hard,128,G,20200120,102,105376,Q,NaN,...,80.0,54.0,15.0,18.0,8.0,12.0,120.0,463.0,221.0,215.0
170,2020-580,Australian Open,Hard,128,G,20200120,103,105807,27,NaN,...,66.0,43.0,26.0,19.0,4.0,8.0,30.0,1422.0,139.0,379.0
171,2020-580,Australian Open,Hard,128,G,20200120,104,106401,23,NaN,...,66.0,50.0,17.0,16.0,4.0,6.0,26.0,1520.0,53.0,990.0

In [6]:
ao20.drop(['winner_seed', 'loser_seed','winner_ht','loser_ht', 'surface','tourney_name','draw_size', 'winner_entry','loser_entry', 'winner_ioc', 'loser_ioc', 'winner_hand','loser_hand','tourney_level','tourney_date', 'w_bpFaced','l_bpFaced', 'best_of', 'loser_rank_points', 'winner_rank_points'], axis=1, inplace=True)

/Users/kbhunjan/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(